# Installing and importing

In [1]:
import pandas as pd
import numpy as np

# Creating a DataFrame and tranfering the data as CSV File

In [ ]:
dict={"name":["pqr","abc","xyz"], "marks":[96,23,53], "rollno":[1,2,3]}

df=pd.DataFrame(dict)
print(df)

df.to_csv("student.csv")

df.to_csv("student2.csv", index=False)

  name  marks  rollno
0  pqr     96       1
1  abc     23       2
2  xyz     53       3

# Only Above 2 rows

In [3]:
df.head(2)

  name  marks  rollno
0  pqr     96       1
1  abc     23       2

# Only Last 2 rows

In [4]:
df.tail(2)

  name  marks  rollno
1  abc     23       2
2  xyz     53       3

# Random 2 rows

In [5]:
df.sample(2)

  name  marks  rollno
0  pqr     96       1
2  xyz     53       3

# All Mathematical Operations

In [5]:
df.describe()

           marks  rollno
count   3.000000     3.0
mean   57.333333     2.0
std    36.692415     1.0
min    23.000000     1.0
25%    38.000000     1.5
50%    53.000000     2.0
75%    74.500000     2.5
max    96.000000     3.0

# Reading a CSV File into Pandas

In [23]:
student3=pd.read_csv("student3.csv")
print(student3)
student3.drop(["Unnamed: 0","Unnamed: 0.1"], axis=1, inplace=True)
print(student3)

   Unnamed: 0.1  Unnamed: 0 Name  Marks  Roll No.
0             0           0  abc     96      1234
1             1           1  pqr     36      2345
2             2           2  xyz     75      3456
3             3           3  efg     14      4567
  Name  Marks  Roll No.
0  abc     96      1234
1  pqr     36      2345
2  xyz     75      3456
3  efg     14      4567

# Slicing

In [25]:
student3["Marks"]

0    96
1    36
2    75
3    14
Name: Marks, dtype: int64

# Always use .loc[] to update data in DataFrame

In [26]:
student3.loc[3, "Marks"] = 24
print(student3)

  Name  Marks  Roll No.
0  abc     96      1234
1  pqr     36      2345
2  xyz     75      3456
3  efg     24      4567

# Updating the CSV File (which we are opening in excel)

In [27]:
student3.to_csv("student3.csv", index=False)

In [29]:
student3.to_csv("student3.csv", index=["first","second","third","fourth"])
student3

  Name  Marks  Roll No.
0  abc     96      1234
1  pqr     36      2345
2  xyz     75      3456
3  efg     24      4567

# Series Data structure in Pandas

In [30]:
ser=pd.Series(np.random.rand(10))

print(ser)

type(ser)

0    0.307115
1    0.761387
2    0.219823
3    0.922487
4    0.929448
5    0.731890
6    0.490983
7    0.226602
8    0.024091
9    0.433807
dtype: float64

pandas.Series

# DataFrame Data structure in pandas

In [31]:
newdf=pd.DataFrame(np.random.rand(10,5))
newdf

          0         1         2         3         4
0  0.695701  0.688048  0.231370  0.591574  0.704776
1  0.385860  0.592126  0.698032  0.638961  0.628945
2  0.358482  0.889977  0.530764  0.351169  0.116799
3  0.238514  0.580430  0.804806  0.141699  0.743376
4  0.989770  0.597000  0.109062  0.096061  0.258263
5  0.950586  0.617788  0.590135  0.622541  0.486316
6  0.771230  0.917998  0.256379  0.894742  0.963352
7  0.849155  0.912035  0.554638  0.199871  0.387813
8  0.332440  0.018149  0.338994  0.115923  0.250154
9  0.891999  0.215384  0.901447  0.319406  0.327982

# type() function

In [32]:
type(newdf)

pandas.DataFrame

In [33]:
newdf.head(2)

          0         1         2         3         4
0  0.695701  0.688048  0.231370  0.591574  0.704776
1  0.385860  0.592126  0.698032  0.638961  0.628945

# .dtypes tell DataType of each entry of a cell

In [15]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

# .columns function

In [16]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

# To convert Pandas Data structure in Numpy Array

In [34]:
newdf.to_numpy()

array([[0.69570085, 0.68804755, 0.23136964, 0.5915737 , 0.70477587],
       [0.3858598 , 0.59212649, 0.69803201, 0.63896064, 0.62894492],
       [0.35848211, 0.88997709, 0.53076411, 0.35116895, 0.11679898],
       [0.23851403, 0.58042964, 0.80480639, 0.14169862, 0.74337612],
       [0.98976989, 0.59699997, 0.10906212, 0.09606087, 0.25826276],
       [0.95058593, 0.6177881 , 0.59013534, 0.62254078, 0.48631553],
       [0.77122985, 0.91799777, 0.25637928, 0.89474165, 0.96335228],
       [0.84915459, 0.91203513, 0.5546382 , 0.19987112, 0.38781338],
       [0.33243968, 0.01814901, 0.33899407, 0.11592311, 0.25015441],
       [0.89199936, 0.21538403, 0.90144745, 0.31940597, 0.32798157]])

# Transpose (swaping of rows and columns)

In [35]:
newdf.T

,0,1,2,3,4,5,6,7,8,9
0,0.695701,0.385860,0.358482,0.238514,0.989770,0.950586,0.771230,0.849155,0.332440,0.891999
1,0.688048,0.592126,0.889977,0.580430,0.597000,0.617788,0.917998,0.912035,0.018149,0.215384
2,0.231370,0.698032,0.530764,0.804806,0.109062,0.590135,0.256379,0.554638,0.338994,0.901447
3,0.591574,0.638961,0.351169,0.141699,0.096061,0.622541,0.894742,0.199871,0.115923,0.319406
4,0.704776,0.628945,0.116799,0.743376,0.258263,0.486316,0.963352,0.387813,0.250154,0.327982

# Sorting the index (axis=0 default) Rows and (axis=1 Columns)

In [36]:
newdf.sort_index(axis=1, ascending=False)

          4         3         2         1         0
0  0.704776  0.591574  0.231370  0.688048  0.695701
1  0.628945  0.638961  0.698032  0.592126  0.385860
2  0.116799  0.351169  0.530764  0.889977  0.358482
3  0.743376  0.141699  0.804806  0.580430  0.238514
4  0.258263  0.096061  0.109062  0.597000  0.989770
5  0.486316  0.622541  0.590135  0.617788  0.950586
6  0.963352  0.894742  0.256379  0.917998  0.771230
7  0.387813  0.199871  0.554638  0.912035  0.849155
8  0.250154  0.115923  0.338994  0.018149  0.332440
9  0.327982  0.319406  0.901447  0.215384  0.891999

# ascending=True (default) and ascending=False (descending)

In [20]:
newdf.sort_index(axis=0, ascending=False)

          0         1         2         3         4
9  0.951899  0.520595  0.031054  0.157603  0.529302
8  0.535921  0.238471  0.949972  0.810693  0.532504
7  0.067878  0.865198  0.702075  0.071967  0.510893
6  0.444668  0.634789  0.016761  0.701774  0.791535
5  0.876438  0.420185  0.524003  0.879663  0.637929
4  0.553725  0.172989  0.763687  0.485764  0.561708
3  0.052503  0.169408  0.287583  0.844490  0.061403
2  0.652805  0.325629  0.848472  0.382451  0.604060
1  0.169257  0.668206  0.002338  0.331028  0.071452
0  0.771322  0.823482  0.679741  0.035379  0.185579

# Acessing the particular value

In [37]:
print(newdf[0][0])

0.6957008537580057

# Check the datastruture type of the particular column

In [22]:
type(newdf[0])

pandas.Series

# View of DataFrame

In [38]:
newdf2=newdf
newdf2.loc[0,0]=100
print(newdf)

            0         1         2         3         4
0  100.000000  0.688048  0.231370  0.591574  0.704776
1    0.385860  0.592126  0.698032  0.638961  0.628945
2    0.358482  0.889977  0.530764  0.351169  0.116799
3    0.238514  0.580430  0.804806  0.141699  0.743376
4    0.989770  0.597000  0.109062  0.096061  0.258263
5    0.950586  0.617788  0.590135  0.622541  0.486316
6    0.771230  0.917998  0.256379  0.894742  0.963352
7    0.849155  0.912035  0.554638  0.199871  0.387813
8    0.332440  0.018149  0.338994  0.115923  0.250154
9    0.891999  0.215384  0.901447  0.319406  0.327982

# Copy of DataFrame

In [39]:
newdf3=newdf.copy()
newdf3.loc[0,0]=2000
print(newdf)

            0         1         2         3         4
0  100.000000  0.688048  0.231370  0.591574  0.704776
1    0.385860  0.592126  0.698032  0.638961  0.628945
2    0.358482  0.889977  0.530764  0.351169  0.116799
3    0.238514  0.580430  0.804806  0.141699  0.743376
4    0.989770  0.597000  0.109062  0.096061  0.258263
5    0.950586  0.617788  0.590135  0.622541  0.486316
6    0.771230  0.917998  0.256379  0.894742  0.963352
7    0.849155  0.912035  0.554638  0.199871  0.387813
8    0.332440  0.018149  0.338994  0.115923  0.250154
9    0.891999  0.215384  0.901447  0.319406  0.327982

# Changing name of columns using list

In [40]:
newdf.columns=list("ABCDE")
newdf

            A         B         C         D         E
0  100.000000  0.688048  0.231370  0.591574  0.704776
1    0.385860  0.592126  0.698032  0.638961  0.628945
2    0.358482  0.889977  0.530764  0.351169  0.116799
3    0.238514  0.580430  0.804806  0.141699  0.743376
4    0.989770  0.597000  0.109062  0.096061  0.258263
5    0.950586  0.617788  0.590135  0.622541  0.486316
6    0.771230  0.917998  0.256379  0.894742  0.963352
7    0.849155  0.912035  0.554638  0.199871  0.387813
8    0.332440  0.018149  0.338994  0.115923  0.250154
9    0.891999  0.215384  0.901447  0.319406  0.327982

# View v/s Copy

In [41]:
newdf.loc[0,0]=300
newdf

            A         B         C         D         E      0
0  100.000000  0.688048  0.231370  0.591574  0.704776  300.0
1    0.385860  0.592126  0.698032  0.638961  0.628945    NaN
2    0.358482  0.889977  0.530764  0.351169  0.116799    NaN
3    0.238514  0.580430  0.804806  0.141699  0.743376    NaN
4    0.989770  0.597000  0.109062  0.096061  0.258263    NaN
5    0.950586  0.617788  0.590135  0.622541  0.486316    NaN
6    0.771230  0.917998  0.256379  0.894742  0.963352    NaN
7    0.849155  0.912035  0.554638  0.199871  0.387813    NaN
8    0.332440  0.018149  0.338994  0.115923  0.250154    NaN
9    0.891999  0.215384  0.901447  0.319406  0.327982    NaN

# Droping the whole column name 0

In [27]:
newdf=newdf.drop(0,axis=1)
newdf

            A         B         C         D         E
0  100.000000  0.823482  0.679741  0.035379  0.185579
1    0.169257  0.668206  0.002338  0.331028  0.071452
2    0.652805  0.325629  0.848472  0.382451  0.604060
3    0.052503  0.169408  0.287583  0.844490  0.061403
4    0.553725  0.172989  0.763687  0.485764  0.561708
5    0.876438  0.420185  0.524003  0.879663  0.637929
6    0.444668  0.634789  0.016761  0.701774  0.791535
7    0.067878  0.865198  0.702075  0.071967  0.510893
8    0.535921  0.238471  0.949972  0.810693  0.532504
9    0.951899  0.520595  0.031054  0.157603  0.529302

# Acessing Method using .loc

In [28]:
newdf.loc[[1,2],["B","C"]]

          B         C
1  0.668206  0.002338
2  0.325629  0.848472

In [29]:
newdf.loc[:,["B","C"]]

          B         C
0  0.823482  0.679741
1  0.668206  0.002338
2  0.325629  0.848472
3  0.169408  0.287583
4  0.172989  0.763687
5  0.420185  0.524003
6  0.634789  0.016761
7  0.865198  0.702075
8  0.238471  0.949972
9  0.520595  0.031054

In [30]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.169257  0.668206  0.002338  0.331028  0.071452
2  0.652805  0.325629  0.848472  0.382451  0.604060

# Applying Condition in .loc

In [31]:
newdf.loc[(newdf["A"]<0.3) & (newdf["B"]>0.5)]

          A         B         C         D         E
1  0.169257  0.668206  0.002338  0.331028  0.071452
7  0.067878  0.865198  0.702075  0.071967  0.510893

# .iloc

In [32]:
newdf.iloc[0,4]

np.float64(0.18557914375571538)

In [33]:
newdf.iloc[0:4]

            A         B         C         D         E
0  100.000000  0.823482  0.679741  0.035379  0.185579
1    0.169257  0.668206  0.002338  0.331028  0.071452
2    0.652805  0.325629  0.848472  0.382451  0.604060
3    0.052503  0.169408  0.287583  0.844490  0.061403

# .drop() function

In [34]:
newdf.drop([0], inplace=True)
print(newdf)

          A         B         C         D         E
1  0.169257  0.668206  0.002338  0.331028  0.071452
2  0.652805  0.325629  0.848472  0.382451  0.604060
3  0.052503  0.169408  0.287583  0.844490  0.061403
4  0.553725  0.172989  0.763687  0.485764  0.561708
5  0.876438  0.420185  0.524003  0.879663  0.637929
6  0.444668  0.634789  0.016761  0.701774  0.791535
7  0.067878  0.865198  0.702075  0.071967  0.510893
8  0.535921  0.238471  0.949972  0.810693  0.532504
9  0.951899  0.520595  0.031054  0.157603  0.529302

In [35]:
newdf.drop(["A","B"],axis=1)

          C         D         E
1  0.002338  0.331028  0.071452
2  0.848472  0.382451  0.604060
3  0.287583  0.844490  0.061403
4  0.763687  0.485764  0.561708
5  0.524003  0.879663  0.637929
6  0.016761  0.701774  0.791535
7  0.702075  0.071967  0.510893
8  0.949972  0.810693  0.532504
9  0.031054  0.157603  0.529302

# .drop(inplace=True) v/s .drop()

In [36]:
newdf

          A         B         C         D         E
1  0.169257  0.668206  0.002338  0.331028  0.071452
2  0.652805  0.325629  0.848472  0.382451  0.604060
3  0.052503  0.169408  0.287583  0.844490  0.061403
4  0.553725  0.172989  0.763687  0.485764  0.561708
5  0.876438  0.420185  0.524003  0.879663  0.637929
6  0.444668  0.634789  0.016761  0.701774  0.791535
7  0.067878  0.865198  0.702075  0.071967  0.510893
8  0.535921  0.238471  0.949972  0.810693  0.532504
9  0.951899  0.520595  0.031054  0.157603  0.529302

# Resetting index again from 0 to row-1

In [37]:
newdf.reset_index()

   index         A         B         C         D         E
0      1  0.169257  0.668206  0.002338  0.331028  0.071452
1      2  0.652805  0.325629  0.848472  0.382451  0.604060
2      3  0.052503  0.169408  0.287583  0.844490  0.061403
3      4  0.553725  0.172989  0.763687  0.485764  0.561708
4      5  0.876438  0.420185  0.524003  0.879663  0.637929
5      6  0.444668  0.634789  0.016761  0.701774  0.791535
6      7  0.067878  0.865198  0.702075  0.071967  0.510893
7      8  0.535921  0.238471  0.949972  0.810693  0.532504
8      9  0.951899  0.520595  0.031054  0.157603  0.529302

In [38]:
newdf.reset_index(drop=True, inplace=True)
print(newdf)

          A         B         C         D         E
0  0.169257  0.668206  0.002338  0.331028  0.071452
1  0.652805  0.325629  0.848472  0.382451  0.604060
2  0.052503  0.169408  0.287583  0.844490  0.061403
3  0.553725  0.172989  0.763687  0.485764  0.561708
4  0.876438  0.420185  0.524003  0.879663  0.637929
5  0.444668  0.634789  0.016761  0.701774  0.791535
6  0.067878  0.865198  0.702075  0.071967  0.510893
7  0.535921  0.238471  0.949972  0.810693  0.532504
8  0.951899  0.520595  0.031054  0.157603  0.529302

# .dropna() dropping the NA Values

In [39]:
newdf.dropna()

          A         B         C         D         E
0  0.169257  0.668206  0.002338  0.331028  0.071452
1  0.652805  0.325629  0.848472  0.382451  0.604060
2  0.052503  0.169408  0.287583  0.844490  0.061403
3  0.553725  0.172989  0.763687  0.485764  0.561708
4  0.876438  0.420185  0.524003  0.879663  0.637929
5  0.444668  0.634789  0.016761  0.701774  0.791535
6  0.067878  0.865198  0.702075  0.071967  0.510893
7  0.535921  0.238471  0.949972  0.810693  0.532504
8  0.951899  0.520595  0.031054  0.157603  0.529302

In [40]:
newdf.loc[:, "B"] = 56
newdf["B"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: B, dtype: bool

In [41]:
newdf.T.shape

(5, 9)

In [42]:
newdf.shape

(9, 5)

In [43]:
newdf.drop_duplicates(subset=["B"])

          A     B         C         D         E
0  0.169257  56.0  0.002338  0.331028  0.071452

In [44]:
newdf.drop_duplicates(subset=["B"], keep="first")

          A     B         C         D         E
0  0.169257  56.0  0.002338  0.331028  0.071452

In [45]:
newdf.drop_duplicates(subset=["B"], keep="last")

          A     B         C         D         E
8  0.951899  56.0  0.031054  0.157603  0.529302

In [46]:
newdf.drop_duplicates(subset=["B"], keep=False)

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [47]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      float64
 1   B       9 non-null      float64
 2   C       9 non-null      float64
 3   D       9 non-null      float64
 4   E       9 non-null      float64
dtypes: float64(5)
memory usage: 492.0 bytes

In [48]:
newdf["A"].value_counts()

A
0.169257    1
0.652805    1
0.052503    1
0.553725    1
0.876438    1
0.444668    1
0.067878    1
0.535921    1
0.951899    1
Name: count, dtype: int64

In [49]:
newdf["A"].value_counts(dropna=True)

A
0.169257    1
0.652805    1
0.052503    1
0.553725    1
0.876438    1
0.444668    1
0.067878    1
0.535921    1
0.951899    1
Name: count, dtype: int64

In [50]:
newdf.notnull()

      A     B     C     D     E
0  True  True  True  True  True
1  True  True  True  True  True
2  True  True  True  True  True
3  True  True  True  True  True
4  True  True  True  True  True
5  True  True  True  True  True
6  True  True  True  True  True
7  True  True  True  True  True
8  True  True  True  True  True

In [42]:
newdf.isnull().sum()

A    0
B    0
C    0
D    0
E    0
0    9
dtype: int64

# create a dataframe which contains only integers with (3,2)
# run following methods
.describe()
.mean()
.corr()
.count()
.max()
.min()
.median()
.std()

In [51]:
newdf4=pd.DataFrame([[2,3],[1,5],[6,4]])
newdf4

   0  1
0  2  3
1  1  5
2  6  4

In [52]:
newdf4.describe()

              0    1
count  3.000000  3.0
mean   3.000000  4.0
std    2.645751  1.0
min    1.000000  3.0
25%    1.500000  3.5
50%    2.000000  4.0
75%    4.000000  4.5
max    6.000000  5.0

In [53]:
newdf4.corr()

          0         1
0  1.000000 -0.188982
1 -0.188982  1.000000

In [54]:
newdf4.median()

0    2.0
1    4.0
dtype: float64

In [55]:
type(newdf4)

pandas.DataFrame

In [56]:
newdf.mean()

A     0.478344
B    56.000000
C     0.458438
D     0.518381
E     0.477865
dtype: float64

# To Read Excel File into Pandas

In [43]:
StudentData=pd.read_excel("StudentData4.xlsx.xlsx")
StudentData

    Name  Marks  City  Roll No.
0  Mohan     95   Goa         3
1  Sohan     34  Pune         5
2    Ram     65   Bly         2
3  Shyam     75   Lko         7

# Reading Specific Sheet

In [58]:
StudentData2=pd.read_excel("StudentData4.xlsx.xlsx",sheet_name="Sheet2")

StudentData2

    Name  Marks  City  Roll No.
0  Reena     54   Bly         5
1  Meena     64  Pune         9
2   Sita     24   Lko        11
3   Gita     86   Goa         4

# Created a new Excel File and Read it into Pandas

In [53]:
TrainData=pd.read_excel("TrainData.xlsx")
TrainData

   Unnamed: 0  TrainNo   Name City From City To
0           0    12345    Ram       Bly     Lko
1           1    23456  Shyam       Goa    Pune
2           2    34567   Sita      Etah     Bly
3           3    45678  Radha    Indore  Bhopal

# Kuch Gadbad ho gyi thi ek new Column create ho gya tha usko delete kiya

In [67]:

TrainData

   TrainNo   Name City From City To
0    12345    Ram       Bly     Lko
1    23456  Shyam       Goa    Pune
2    34567   Sita      Etah     Bly
3    45678  Radha    Indore  Bhopal

# Replacing Gita with Radha

In [ ]:
TrainData.iloc[3,2]="Radha"
TrainData

   Unnamed: 0  TrainNo   Name City From City To
0           0    12345    Ram       Bly     Lko
1           1    23456  Shyam       Goa    Pune
2           2    34567   Sita      Etah     Bly
3           3    45678  Radha    Indore  Bhopal

# Now edit it into Excel File

In [68]:
TrainData.to_excel("TrainData.xlsx", index=False)