# Practicing Pandas

In [2]:
import pandas as pd
# print(pd.__version__)
# print(pd.__file__)
# print(pd.__path__)
# print(pd.__spec__)
# print(pd.__name__)
# print(pd.__doc__)
# print(pd.__all__)
print("Successfully imported pandas")

Successfully imported pandas

In [17]:
data={"ID":[1,2,3,4,5],
      "Name":["Alice","Bob","Charlie","David","Eve"],
      "Salary":[67000,48000,93000,76000,59000],
      "Age":[25,30,35,40,45],
      "City":["New York","Los Angeles","Chicago","Houston","Phoenix"]}

df=pd.DataFrame(data)
df.set_index("ID", inplace=True)
df

       Name  Salary  Age         City
ID
1     Alice   67000   25     New York
2       Bob   48000   30  Los Angeles
3   Charlie   93000   35      Chicago
4     David   76000   40      Houston
5       Eve   59000   45      Phoenix

In [18]:
# df.sum()
df.sum(numeric_only=True)

Salary    343000
Age          175
dtype: int64

In [19]:
df.max(numeric_only=True)

Salary    93000
Age          45
dtype: int64

In [20]:
df.min(numeric_only=True)

Salary    48000
Age          25
dtype: int64

In [23]:
df.mean(numeric_only=True)

Salary    68600.0
Age          35.0
dtype: float64

In [24]:
df.describe()

             Salary        Age
count      5.000000   5.000000
mean   68600.000000  35.000000
std    17096.783323   7.905694
min    48000.000000  25.000000
25%    59000.000000  30.000000
50%    67000.000000  35.000000
75%    76000.000000  40.000000
max    93000.000000  45.000000

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 1 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Salary  5 non-null      int64
 2   Age     5 non-null      int64
 3   City    5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [28]:
df["Age"].corr(df["Salary"])

np.float64(0.1109779869250491)

In [31]:
df.sample(3)

       Name  Salary  Age         City
ID
2       Bob   48000   30  Los Angeles
3   Charlie   93000   35      Chicago
5       Eve   59000   45      Phoenix

In [32]:
df.columns

Index(['Name', 'Salary', 'Age', 'City'], dtype='str')

In [34]:
df.isnull().sum()

Name      0
Salary    0
Age       0
City      0
dtype: int64

In [35]:
df.shape

(5, 4)

In [36]:
df.size

20

In [37]:
df.dtypes

Name        str
Salary    int64
Age       int64
City        str
dtype: object

In [40]:
df.T

ID             1            2        3        4        5
Name       Alice          Bob  Charlie    David      Eve
Salary     67000        48000    93000    76000    59000
Age           25           30       35       40       45
City    New York  Los Angeles  Chicago  Houston  Phoenix

In [43]:
df.add(df)

              Name  Salary  Age                    City
ID
1       AliceAlice  134000   50        New YorkNew York
2           BobBob   96000   60  Los AngelesLos Angeles
3   CharlieCharlie  186000   70          ChicagoChicago
4       DavidDavid  152000   80          HoustonHouston
5           EveEve  118000   90          PhoenixPhoenix

In [46]:
df.merge(df, on="ID", suffixes=("_left", "_right"))

,Name_left,Salary_left,Age_left,City_left,Name_right,Salary_right,Age_right,City_right
ID,,,,,,,,
1,Alice,67000,25,New York,Alice,67000,25,New York
2,Bob,48000,30,Los Angeles,Bob,48000,30,Los Angeles
3,Charlie,93000,35,Chicago,Charlie,93000,35,Chicago
4,David,76000,40,Houston,David,76000,40,Houston
5,Eve,59000,45,Phoenix,Eve,59000,45,Phoenix